{
 "title": "Sensor 1",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Luftqualität",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  channel_id AS metric,\n  measurement\nFROM timeseries.measurements\nWHERE\n  $__timeFilter(timestamp) AND\n  channel_id = 'h4o/s1/co2'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  channel_id AS metric,\n  measurement\nFROM timeseries.measurements\nWHERE\n  $__timeFilter(timestamp) AND\n  channel_id = 'h4o/s1/temp'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Relative Luftfeuchtigkeit",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  channel_id AS metric,\n  measurement\nFROM timeseries.measurements\nWHERE\n  $__timeFilter(timestamp) AND\n  channel_id = 'h4o/s1/hum'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Luftdruck",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  channel_id AS metric,\n  measurement\nFROM timeseries.measurements\nWHERE\n  $__timeFilter(timestamp) AND\n  channel_id = 'h4o/s1/press'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "H4O - Sensor 1 - CO₂/Temp",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "yaxes": [
    { "format": "ppm", "label": "Luftqualität (CO₂)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  channel_id AS metric,\n  measurement\nFROM timeseries.measurements\nWHERE\n  $__timeFilter(\"timestamp\") AND channel_id in ('h4o/s1/temp', 'h4o/s1/co2')\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "H4O - Sensor 1 - Press/Hum",
   "type": "graph",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "yaxes": [
    { "format": "pressurehpa", "label": "Luftdruck" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  channel_id AS metric,\n  measurement\nFROM timeseries.measurements\nWHERE\n  $__timeFilter(\"timestamp\") AND channel_id in ('h4o/s1/press', 'h4o/s1/hum')\nORDER BY 1,2"
    }
   ]
  }
 ]
}